### ISSUE TITLE
Sticky Mode doesn't work if section background is a picture

### ISSUE THREAD

**Issue by stormanh** [RedEchidnaUK/Table-of-Contents#13]
If the background for the section is a picture (as shown below), the sticky mode functionality stops working.
![image](https://github.com/user-attachments/assets/b083bebd-b17b-4e85-80dc-62787cdb6788)

**Comment by RedEchidnaUK** [comment]
Thank you for the report. 

I can confirm it is a bug due to a change in Microsoft's HTML. This is the main problem with the 'Sticky' functionality, it's liable to break with every change Microsoft make as I have modify their HTML to produce the effect.

I'll try and look at it at some point, but I can't say when that will be.

**Comment by RedEchidnaUK** [comment]
@stormanh I've released a new version which should fix the issue.

**Comment by stormanh** [comment]
@RedEchidnaUK Confirmed this issue is now fixed, thank you!
